import * as fc from 'fast-check';
import { StructuredLogger } from '../../lib/monitoring/structured-logger';
import { LogLevel, LogContext } from '../../lib/monitoring/types';

/**
 * Property-Based Tests for Structured Logging
 * 
 * These tests validate universal properties for structured logging:
 * - Property 3: Structured Log Format Compliance
 * - Property 4: Log Entry Correlation
 * 
 * Feature: monitoring-and-observability
 * Validates: Requirements 5.4, 5.5, 5.6
 */

describe('Structured Logging Properties', () => {
  /**
   * Helper function to capture console.log output
   */
  const captureConsoleLog = (fn: () => void): string => {
    const originalLog = console.log;
    let output = '';
    
    console.log = (message: string) => {
      output = message;
    };
    
    try {
      fn();
    } finally {
      console.log = originalLog;
    }
    
    return output;
  };

  /**
   * Property 3: Structured Log Format Compliance
   * 
   * Universal Property: For any log entry generated by any component,
   * the log entry should be valid JSON containing required fields:
   * timestamp, level, message, component, and requestId.
   * 
   * Validates: Requirements 5.4, 5.5
   */
  test('Property 3: All log entries are valid JSON with required fields', () => {
    fc.assert(
      fc.property(
        // Generate random log contexts
        fc.record({
          level: fc.constantFrom(LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR),
          message: fc.string({ minLength: 1, maxLength: 500 }),
          component: fc.string({ minLength: 1, maxLength: 100 }),
          requestId: fc.uuid(),
          userId: fc.option(fc.uuid(), { nil: undefined }),
          operation: fc.option(fc.string({ minLength: 1, maxLength: 50 }), { nil: undefined }),
          duration: fc.option(fc.integer({ min: 0, max: 60000 }), { nil: undefined }),
          metadata: fc.option(
            fc.dictionary(
              fc.string({ minLength: 1, maxLength: 20 }),
              fc.oneof(
                fc.string(),
                fc.integer(),
                fc.boolean(),
                fc.constant(null)
              )
            ),
            { nil: undefined }
          ),
        }),
        (logData) => {
          const logger = new StructuredLogger();
          
          // Build context from generated data
          const context: LogContext = {
            component: logData.component,
            requestId: logData.requestId,
            userId: logData.userId,
            operation: logData.operation,
            duration: logData.duration,
            metadata: logData.metadata,
          };
          
          // Capture the log output
          const output = captureConsoleLog(() => {
            logger.log(logData.level, logData.message, context);
          });
          
          // Property 1: Output must be valid JSON
          let parsed;
          try {
            parsed = JSON.parse(output);
          } catch (e) {
            throw new Error(`Log output is not valid JSON: ${output}`);
          }
          
          // Property 2: Must have required fields
          expect(parsed).toHaveProperty('timestamp');
          expect(parsed).toHaveProperty('level');
          expect(parsed).toHaveProperty('message');
          expect(parsed).toHaveProperty('component');
          
          // Property 3: timestamp must be valid ISO 8601 format
          expect(() => new Date(parsed.timestamp)).not.toThrow();
          expect(new Date(parsed.timestamp).toISOString()).toBe(parsed.timestamp);
          
          // Property 4: level must match input
          expect(parsed.level).toBe(logData.level);
          
          // Property 5: message must be present (may be sanitized)
          expect(typeof parsed.message).toBe('string');
          expect(parsed.message.length).toBeGreaterThan(0);
          
          // Property 6: component must match input
          expect(parsed.component).toBe(logData.component);
          
          // Property 7: requestId must be present when provided
          if (logData.requestId) {
            expect(parsed).toHaveProperty('requestId');
            expect(parsed.requestId).toBe(logData.requestId);
          }
          
          // Property 8: userId must be present when provided
          if (logData.userId) {
            expect(parsed).toHaveProperty('userId');
            // userId may be sanitized, but must be present
            expect(typeof parsed.userId).toBe('string');
          }
          
          // Property 9: operation must be present when provided
          if (logData.operation) {
            expect(parsed.operation).toBe(logData.operation);
          }
          
          // Property 10: duration must be present when provided
          if (logData.duration !== undefined) {
            expect(parsed.duration).toBe(logData.duration);
          }
          
          // Property 11: metadata must be present when provided
          if (logData.metadata && Object.keys(logData.metadata).length > 0) {
            expect(parsed).toHaveProperty('metadata');
            expect(typeof parsed.metadata).toBe('object');
          }
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 3 (variant): Test with info() convenience method
   */
  test('Property 3: info() method produces valid structured logs', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 500 }),
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.uuid(),
        (message, component, requestId) => {
          const logger = new StructuredLogger();
          
          const output = captureConsoleLog(() => {
            logger.info(message, { component, requestId });
          });
          
          const parsed = JSON.parse(output);
          
          expect(parsed).toHaveProperty('timestamp');
          expect(parsed.level).toBe(LogLevel.INFO);
          expect(parsed).toHaveProperty('message');
          expect(parsed.component).toBe(component);
          expect(parsed.requestId).toBe(requestId);
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 3 (variant): Test with warn() convenience method
   */
  test('Property 3: warn() method produces valid structured logs', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 500 }),
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.uuid(),
        (message, component, requestId) => {
          const logger = new StructuredLogger();
          
          const output = captureConsoleLog(() => {
            logger.warn(message, { component, requestId });
          });
          
          const parsed = JSON.parse(output);
          
          expect(parsed).toHaveProperty('timestamp');
          expect(parsed.level).toBe(LogLevel.WARN);
          expect(parsed).toHaveProperty('message');
          expect(parsed.component).toBe(component);
          expect(parsed.requestId).toBe(requestId);
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 3 (variant): Test with error() method
   */
  test('Property 3: error() method produces valid structured logs with error details', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 500 }),
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.string({ minLength: 1, maxLength: 200 }),
        fc.uuid(),
        (message, component, errorMessage, requestId) => {
          const logger = new StructuredLogger();
          const error = new Error(errorMessage);
          
          const output = captureConsoleLog(() => {
            logger.error(message, error, { component, requestId });
          });
          
          const parsed = JSON.parse(output);
          
          expect(parsed).toHaveProperty('timestamp');
          expect(parsed.level).toBe(LogLevel.ERROR);
          expect(parsed).toHaveProperty('message');
          expect(parsed.component).toBe(component);
          expect(parsed.requestId).toBe(requestId);
          
          // Error logs must include error details
          expect(parsed).toHaveProperty('error');
          expect(parsed.error).toHaveProperty('message');
          expect(parsed.error).toHaveProperty('stack');
          expect(parsed.error).toHaveProperty('type');
          expect(parsed.error.type).toBe('Error');
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 3 (edge case): Test with empty optional fields
   */
  test('Property 3: Logs with minimal context still produce valid JSON', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR),
        fc.string({ minLength: 1, maxLength: 500 }),
        fc.string({ minLength: 1, maxLength: 100 }),
        (level, message, component) => {
          const logger = new StructuredLogger();
          
          const output = captureConsoleLog(() => {
            logger.log(level, message, { component });
          });
          
          const parsed = JSON.parse(output);
          
          // Must have required fields even with minimal context
          expect(parsed).toHaveProperty('timestamp');
          expect(parsed).toHaveProperty('level');
          expect(parsed).toHaveProperty('message');
          expect(parsed).toHaveProperty('component');
          
          // Optional fields should not be present
          expect(parsed.requestId).toBeUndefined();
          expect(parsed.userId).toBeUndefined();
          expect(parsed.operation).toBeUndefined();
          expect(parsed.duration).toBeUndefined();
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 3 (PII sanitization): Test that PII is redacted
   */
  test('Property 3: PII is sanitized from log messages', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.string({ minLength: 1, maxLength: 100 }),
        (component, requestId) => {
          const logger = new StructuredLogger();
          
          // Messages containing PII patterns
          const piiMessages = [
            'User phone: 555-123-4567',
            'Email: user@example.com',
            'Card: 1234-5678-9012-3456',
            'SSN: 123-45-6789',
          ];
          
          for (const message of piiMessages) {
            const output = captureConsoleLog(() => {
              logger.info(message, { component, requestId });
            });
            
            const parsed = JSON.parse(output);
            
            // PII should be redacted
            expect(parsed.message).toContain('[REDACTED]');
            expect(parsed.message).not.toMatch(/\d{3}[-.]?\d{3}[-.]?\d{4}/); // Phone
            expect(parsed.message).not.toMatch(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}/); // Email
            expect(parsed.message).not.toMatch(/\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}/); // Card
            expect(parsed.message).not.toMatch(/\d{3}-\d{2}-\d{4}/); // SSN
          }
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 3 (size limit): Test that oversized logs are truncated
   */
  test('Property 3: Oversized log entries are truncated gracefully', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1, maxLength: 100 }),
        fc.uuid(),
        (component, requestId) => {
          const logger = new StructuredLogger();
          
          // Create a very large metadata object (>256 KB)
          const largeMetadata: Record<string, string> = {};
          for (let i = 0; i < 10000; i++) {
            largeMetadata[`key${i}`] = 'x'.repeat(100);
          }
          
          const output = captureConsoleLog(() => {
            logger.info('Test message', {
              component,
              requestId,
              metadata: largeMetadata,
            });
          });
          
          const parsed = JSON.parse(output);
          
          // Must still be valid JSON
          expect(parsed).toHaveProperty('timestamp');
          expect(parsed).toHaveProperty('level');
          expect(parsed).toHaveProperty('message');
          expect(parsed).toHaveProperty('component');
          
          // Should have truncation indicator
          if (parsed.metadata) {
            expect(parsed.metadata._truncated).toBe(true);
            expect(parsed.metadata._originalSize).toBeGreaterThan(256 * 1024);
          }
          
          // Output size should be under limit
          const outputSize = Buffer.byteLength(output, 'utf8');
          expect(outputSize).toBeLessThanOrEqual(256 * 1024);
        }
      ),
      { numRuns: 5 } // Fewer runs for performance
    );
  });

  /**
   * Property 4: Log Entry Correlation
   * 
   * Universal Property: For any log entry where user context is available,
   * the log entry should include the userId field for correlation.
   * 
   * Validates: Requirements 5.6
   */
  test('Property 4: Log entries include userId when user context is available', () => {
    fc.assert(
      fc.property(
        // Generate random log contexts with userId
        fc.record({
          level: fc.constantFrom(LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR),
          message: fc.string({ minLength: 1, maxLength: 500 }),
          component: fc.string({ minLength: 1, maxLength: 100 }),
          requestId: fc.uuid(),
          userId: fc.uuid(), // Always present for this property test
          operation: fc.option(fc.string({ minLength: 1, maxLength: 50 }), { nil: undefined }),
        }),
        (logData) => {
          const logger = new StructuredLogger();
          
          // Build context with userId
          const context: LogContext = {
            component: logData.component,
            requestId: logData.requestId,
            userId: logData.userId,
            operation: logData.operation,
          };
          
          // Capture the log output
          const output = captureConsoleLog(() => {
            logger.log(logData.level, logData.message, context);
          });
          
          const parsed = JSON.parse(output);
          
          // Property: When userId is provided in context, it must be present in the log entry
          expect(parsed).toHaveProperty('userId');
          expect(typeof parsed.userId).toBe('string');
          expect(parsed.userId.length).toBeGreaterThan(0);
          
          // The userId should be present (may be sanitized/hashed for privacy)
          // but must exist for correlation purposes
          expect(parsed.userId).toBeDefined();
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 4 (variant): Test correlation across multiple log entries
   */
  test('Property 4: Multiple log entries with same userId maintain correlation', () => {
    fc.assert(
      fc.property(
        fc.uuid(), // Same userId for all logs
        fc.string({ minLength: 1, maxLength: 100 }), // component
        fc.array(
          fc.record({
            level: fc.constantFrom(LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR),
            message: fc.string({ minLength: 1, maxLength: 200 }),
            requestId: fc.uuid(),
          }),
          { minLength: 2, maxLength: 5 }
        ),
        (userId, component, logEntries) => {
          const logger = new StructuredLogger();
          const outputs: string[] = [];
          
          // Generate multiple log entries with the same userId
          for (const entry of logEntries) {
            const output = captureConsoleLog(() => {
              logger.log(entry.level, entry.message, {
                component,
                requestId: entry.requestId,
                userId,
              });
            });
            outputs.push(output);
          }
          
          // Parse all outputs
          const parsedLogs = outputs.map(output => JSON.parse(output));
          
          // Property: All log entries should have the userId field
          for (const parsed of parsedLogs) {
            expect(parsed).toHaveProperty('userId');
            expect(typeof parsed.userId).toBe('string');
            expect(parsed.userId.length).toBeGreaterThan(0);
          }
          
          // Property: All log entries should have the same userId value (for correlation)
          const userIds = parsedLogs.map(log => log.userId);
          const uniqueUserIds = new Set(userIds);
          expect(uniqueUserIds.size).toBe(1); // All should be the same
        }
      ),
      { numRuns: 15 }
    );
  });

  /**
   * Property 4 (variant): Test correlation with requestId and userId together
   */
  test('Property 4: Log entries include both requestId and userId for full correlation', () => {
    fc.assert(
      fc.property(
        fc.record({
          level: fc.constantFrom(LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR),
          message: fc.string({ minLength: 1, maxLength: 500 }),
          component: fc.string({ minLength: 1, maxLength: 100 }),
          requestId: fc.uuid(),
          userId: fc.uuid(),
        }),
        (logData) => {
          const logger = new StructuredLogger();
          
          const output = captureConsoleLog(() => {
            logger.log(logData.level, logData.message, {
              component: logData.component,
              requestId: logData.requestId,
              userId: logData.userId,
            });
          });
          
          const parsed = JSON.parse(output);
          
          // Property: Both correlation IDs must be present
          expect(parsed).toHaveProperty('requestId');
          expect(parsed).toHaveProperty('userId');
          
          // Both should be non-empty strings
          expect(typeof parsed.requestId).toBe('string');
          expect(typeof parsed.userId).toBe('string');
          expect(parsed.requestId.length).toBeGreaterThan(0);
          expect(parsed.userId.length).toBeGreaterThan(0);
          
          // requestId should match exactly (not sanitized)
          expect(parsed.requestId).toBe(logData.requestId);
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 4 (edge case): Test that logs without userId don't have the field
   */
  test('Property 4: Log entries without user context do not include userId', () => {
    fc.assert(
      fc.property(
        fc.record({
          level: fc.constantFrom(LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR),
          message: fc.string({ minLength: 1, maxLength: 500 }),
          component: fc.string({ minLength: 1, maxLength: 100 }),
          requestId: fc.uuid(),
        }),
        (logData) => {
          const logger = new StructuredLogger();
          
          // Context without userId
          const output = captureConsoleLog(() => {
            logger.log(logData.level, logData.message, {
              component: logData.component,
              requestId: logData.requestId,
              // No userId provided
            });
          });
          
          const parsed = JSON.parse(output);
          
          // Property: When userId is not provided, it should not be in the output
          // (or should be undefined/null, not an empty string)
          if (parsed.userId !== undefined) {
            expect(parsed.userId).toBeNull();
          }
        }
      ),
      { numRuns: 20 }
    );
  });

  /**
   * Property 4 (sessionId correlation): Test sessionId correlation for mobile clients
   */
  test('Property 4: Log entries include sessionId when available for mobile correlation', () => {
    fc.assert(
      fc.property(
        fc.record({
          level: fc.constantFrom(LogLevel.INFO, LogLevel.WARN, LogLevel.ERROR),
          message: fc.string({ minLength: 1, maxLength: 500 }),
          component: fc.string({ minLength: 1, maxLength: 100 }),
          requestId: fc.uuid(),
          userId: fc.uuid(),
          sessionId: fc.uuid(),
        }),
        (logData) => {
          const logger = new StructuredLogger();
          
          const output = captureConsoleLog(() => {
            logger.log(logData.level, logData.message, {
              component: logData.component,
              requestId: logData.requestId,
              userId: logData.userId,
              sessionId: logData.sessionId,
            });
          });
          
          const parsed = JSON.parse(output);
          
          // Property: All correlation IDs should be present
          expect(parsed).toHaveProperty('requestId');
          expect(parsed).toHaveProperty('userId');
          expect(parsed).toHaveProperty('sessionId');
          
          // All should be non-empty strings
          expect(typeof parsed.requestId).toBe('string');
          expect(typeof parsed.userId).toBe('string');
          expect(typeof parsed.sessionId).toBe('string');
          expect(parsed.requestId.length).toBeGreaterThan(0);
          expect(parsed.userId.length).toBeGreaterThan(0);
          expect(parsed.sessionId.length).toBeGreaterThan(0);
        }
      ),
      { numRuns: 20 }
    );
  });
});
